version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # Assuming NestJS runs on port 3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=shopperpassword
      - POSTGRES_DB=shopper
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
#   pgadmin:
#     image: dpage/pgadmin4
#     environment:
#  - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#  - PGADMIN_DEFAULT_PASSWORD=password
#     ports:
#  - 5050:80
#     depends_on:
#  - db
