version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development/production stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    # environment:
    # - DATABASE_URL=postgresql://root:shopperpassword@postgres:5432/shopper?schema=public
    # Run a command against the development stage of the image
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm run start:dev
      "
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=shopper
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=shopperpassword
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 5s
      retries: 15

volumes:
  db:
